name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master  # Set this to your default branch
  pull_request:
    branches:
      - master  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x' # Specify your Node.js version

    - name: npm install, build
      run: |
        npm install
        npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stoicjournal' # Set your app name here
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EC827B5239F84C7D99B39C664591A70E }}
        package: './build'
